name: food_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  openfoodfacts: ^3.21.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  build_runner: ^2.4.15
  json_annotation: ^4.9.0
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  simple_barcode_scanner: ^0.3.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.8.0
  firebase_app_check: ^0.3.2+6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
    
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  import_sorter: ^4.6.0
  very_good_analysis: ^8.0.0


flutter:
  assets:
    - ./dotenv
  uses-material-design: true


