name: food_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  openfoodfacts: ^3.21.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  build_runner: ^2.4.15
  json_annotation: ^4.9.0
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  simple_barcode_scanner: ^0.3.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.8.0
  firebase_app_check: ^0.3.2+6
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.16.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  very_good_analysis: ^8.0.0
  freezed: ^3.0.6


flutter:
  assets:
    - ./.env
    - assets/icon/mipmap-hdpi/
    - assets/icon/mipmap-mdpi/
    - assets/icon/mipmap-xhdpi/
    - assets/icon/mipmap-xxhdpi/
    - assets/icon/mipmap-xxxhdpi/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/aguacate.png"

